name: Testing the commit
on:
    push:
        branches: [main]

jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: check out repo
            - uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{secrets.HOST}}
                username: ubuntu
                key: ${{secrets.KEY}}
                port: 22
                script: |
                    ls
                    cd the-diary-app/
                    ls
                    npm install -g pnpm
                    pnpm install
                    npx prisma generate
                    pnpm run build
                    pnpm run start 
                    